# Generated by Django 4.1.6 on 2023-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0003_remove_courses_id_alter_courses_coursename_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='trainer',
            field=models.ManyToManyField(default='Null', to='riaapp.trainer'),
        ),
    ]
