# Generated by Django 4.1.6 on 2023-02-15 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0004_register_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='trainer',
        ),
        migrations.AddField(
            model_name='register',
            name='trainer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='riaapp.trainer'),
        ),
    ]
