# Generated by Django 4.1.6 on 2023-02-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0005_remove_register_trainer_register_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='riaapp.trainer'),
        ),
    ]
