# Generated by Django 4.1.6 on 2023-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0007_attendace'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='stars',
            field=models.IntegerField(default=3),
        ),
    ]
